version: '2'
services:
  web:
    build: .
    ports:
        - "8080:8080"
    depends_on:
        - minio
    networks:
      vpcbr:
         ipv4_address: 172.18.18.09
    volumes:
     - /mnt/source:/source
 
  minio:
    image:  minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - /mnt/data:/data
    command: server /data --compat
    networks:
      vpcbr:
       ipv4_address: 172.18.18.10

volumes:
  data:
networks:
  vpcbr:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.18.0/24
        gateway: 172.18.18.1
